name: mgr
channels:
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - colorama
  - numba
  - matplotlib
  - openblas
  - pandas
  - scikit-image
  - numpy
  - scikit-learn
  - scipy
  - tqdm
  - wandb
  - wheel
  - ipython
  - pip
  - pip:
      - jupyter-client
      - jupyter-core
      - jupyterlab
      - randomname
      - kornia
      - opencv_python_headless
      - joblib
      - pillow
      - albumentations
      - torchmetrics
      - adabelief_pytorch
      - segmentation_models_pytorch