Region: eu-north-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-0b60e3ee410d77f39
  Ssh:
    KeyName: oscar-pirate
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: pirate-queue
    ComputeResources:
    - Name: g4dnxlarge
      Instances:
      - InstanceType: g4dn.xlarge
      MinCount: 0
      MaxCount: 4
    Networking:
      SubnetIds:
      - subnet-03e6015c2d68392db
