HeadNode:
  InstanceType: t3.large
  Networking:
    SubnetId: subnet-0d14aa3e1f4923347
  LocalStorage:
    RootVolume:
      Size: 50
  Roles:
    Policies:
      - Statement:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:ListBucket
              - s3:PutObject
            Resource:
              - arn:aws:s3:::bachelor-pirate-data
              - arn:aws:s3:::bachelor-pirate-data/*

Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: GPUQueue
      ComputeResources:
        - Name: GPUInstances
          InstanceType: g4dn.xlarge
          MinCount: 0
          MaxCount: 4
          Efa:
            Enabled: true
      Networking:
        SubnetIds:
          - subnet-0d14aa3e1f4923347
SharedStorage:
  - Name: ImageDataset
    MountDir: /shared/dataset
    StorageType: Efs
  - Name: ModelCheckpoints
    MountDir: /shared/checkpoints
    StorageType: FsxLustre
Image:
  Os: alinux2
Monitoring:
  DetailedMonitoring: true