Region: eu-north-1
Image:
  Os: alinux2
HeadNode:
  InstanceType: t3.micro
  Networking:
    SubnetId: subnet-08d9f539c8224772c
  Ssh:
    KeyName: oscar-pirate
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: queue1
    ComputeResources:
    - Name: t3micro
      Instances:
      - InstanceType: t3.micro
      MinCount: 0
      MaxCount: 10
    Networking:
      SubnetIds:
      - subnet-090b153697a9bac8e
